miuride/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from miuride_app.urls import urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('miuride_app.urls', namespace='index')),
]

miuride_app/urls.py
from django.conf.urls import url, include

from . import views
from .views import router

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'post_location', views.post_location, name='post_location'),
    url(r'^register_tourism_point/$', views.register_tourism_point, name='register_tourism_point'),
    url(r'^api/v1/', include(router.urls))
]

miuride_app/models.py
from django.db import models
import uuid


class TourismPoint(models.Model):
    name = models.CharField('観光ポイント名', max_length=32)
    description = models.TextField('詳細説明', max_length=256)
    lat = models.DecimalField(max_digits=12, decimal_places=8)
    lng = models.DecimalField(max_digits=12, decimal_places=8)

    def __str__(self):
        return self.name

    @property
    def categories(self):
        return TourismCategory.objects.filter(tourism_point=self)


class TourismCategory(models.Model):
    name = models.CharField('カテゴリ名', max_length=32)
    tourism_point = models.ForeignKey(TourismPoint, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class UUID(models.Model):
    uuid = models.CharField(max_length=36, default=str(uuid.uuid4()))


class Breadcrumb(models.Model):
    uuid = models.ForeignKey(UUID)
    created_at = models.DateTimeField(auto_created=True)
    lat = models.DecimalField(max_digits=12, decimal_places=8)
    lng = models.DecimalField(max_digits=12, decimal_places=8)

    def __str__(self):
        return self.uuid + ':' + '{},{}'.format(self.lat, self.lng)

miuride_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.conf import settings
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework import routers
import django_filters
from django_filters.rest_framework import DjangoFilterBackend

from .models import TourismPoint
from .models import TourismCategory
from .models import UUID
from .models import Breadcrumb
from miuride_app.utils.geometry import get_distance

from .serializer import TourismPointSerializer


def index(request):
    key = settings.GCP_API_KEY
    return render(request, 'miuride_app/index.html', {'key': key})


def post_location(request):
    if request.method == 'POST':
        if 'uuid' in request.session:
            uuid = UUID.objects.get(uuid=request.session['uuid'])
        else:
            uuid = UUID()
            request.session['uuid'] = uuid
        lat = request.POST['lat']
        lng = request.POST['lng']
        location = Breadcrumb(uuid=uuid, lat=lat, lng=lng)
        location.save()
    return JsonResponse({})


def register_tourism_point(request):
    error = None
    if request.method == 'POST':
        try:
            name = request.POST['name']
            description = request.POST['description']
            lat = request.POST['lat']
            lng = request.POST['lng']
            categories = request.POST.getlist('category')
            tp = TourismPoint(name=name, description=description, lat=lat, lng=lng)
            tp.save()
            for category in categories:
                tc = TourismCategory(name=category, tourism_point=tp)
                tc.save()
        except Exception as e:
            error = e
    return render(request, 'miuride_app/register_tourism_point.html', {'error': error})


class TourismFilter(django_filters.rest_framework.FilterSet):
    category = django_filters.CharFilter(name='tourismcategory__name')
    in_range = django_filters.NumberFilter(name='in_range', method='filter_in_range')
    filter_fields = ('name', 'category', 'in_range')

    def filter_in_range(self, queryset, name, value):
        print(queryset)
        print(name)
        print(value)
        return queryset

    class Meta:
        model = TourismPoint
        fields = ['category', 'name', 'in_range']


class TourismPointViewSet(viewsets.ModelViewSet):
    serializer_class = TourismPointSerializer
    permission_classes = (permissions.AllowAny, )
    queryset = TourismPoint.objects.all()
    filter_backends = (DjangoFilterBackend,)
    filter_class = TourismFilter


router = routers.DefaultRouter()
router.register(r'tourism_point', TourismPointViewSet, base_name='tourism_point')

miuride_app/templates/miuride_app/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <link rel="stylesheet" href="{% static 'miuride_app/css/index.css' %}">
    <script type="text/javascript" src="{% static 'miuride_app/js/jquery-3.2.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'miuride_app/js/index.js' %}"></script>
    <script type="text/javascript" src="{% static 'miuride_app/js/speech.js' %}"></script>
    <script
      async defer
      src="https://maps.googleapis.com/maps/api/js?key={{ key }}">
    </script>
    <title>みうライド</title>
  </head>
  <body>
    <div class="wrapper">
      <div id="startPage" class="started">
        <a class="started__content" onclick="starting()">
          <img class="started__content__image" src="{% static 'miuride_app/images/logo.png' %}" alt="">
          <p class="started__content__text">Tap to Start</p>
        </a>
      </div>
      <div id="main" class="main">
        <div class="main__tab">
          <div class="tabMenu">
            <h3 class="tabMenu__title">カテゴリ</h3>
            <ul class="tabMenu__list">
              <li class="tabMenu__list__item" onclick="getAndLocatePoints();"><a class="tabMenu__list__item__anchor" href="#">すべて</a></li>
              <li class="tabMenu__list__item is-active" onclick="getAndLocatePoints('tourism');"><a class="tabMenu__list__item__anchor" href="#">観光名所</a></li>
              <li class="tabMenu__list__item" onclick="getAndLocatePoints('gourmet');"><a class="tabMenu__list__item__anchor" href="#">食事処</a></li>
              <li class="tabMenu__list__item" onclick="getAndLocatePoints('public');"><a class="tabMenu__list__item__anchor" href="#">公共施設</a></li>
              <li class="tabMenu__list__item" onclick="getAndLocatePoints('emergency');"><a class="tabMenu__list__item__anchor" href="#">緊急</a></li>
            </ul>
          </div>
        </div>
        <div class="main__content">
          <div class="header">
            <div class="header__btnWrapper">
              <div class="header__btnWrapper__btn" onclick="tabSwitch(this)"></div>
              <hr class="header__btnWrapper__bar is-first">
              <hr class="header__btnWrapper__bar is-second">
              <hr class="header__btnWrapper__bar is-third">
            </div>
            <div class="header__title">
              <img src="{% static 'miuride_app/images/title.png' %}" alt="みうライド">
            </div>
          </div>
          <div id="map-canvas" class="gmap"></div>
          <script type="text/javascript" src="{% static 'miuride_app/js/gmap.js' %}"></script>
        </div>
      </div>
    </div>
  </body>
</html>

miuride_app/templates/miuride_app/register_tourism_point.html
{% load static %}
<html>
<head>
  <title>新規登録</title>
  <link rel="stylesheet" href="{% static 'miuride_app/css/register.css' %}">
</head>
<body>

<div class="wrapper">
  <h1>データ入力画面</h1>
  <div class="inputContent">
    {% if error %}{{ error }}{% endif %}
    <form action="{% url 'index:register_tourism_point' %}" method="post">
      <div class="inputContent__item">
        <label for="name">観光ポイント名</label>
        <input id="name" type="text" name="name">
      </div>
      <div class="inputContent__item">
        <label for="description">詳細説明</label>
        <input id="description" type="text" name="description">
      </div>
      <div class="inputContent__item">
        <label for="lat">緯度</label>
        <input id="lat" type="text" name="lat">
      </div>
      <div class="inputContent__item">
        <label for="lng">経度</label>
        <input id="lng" type="text" name="lng">
      </div>
      {% csrf_token %}
      <div class="inputContent__item">
        <label for="category">カテゴリー</label>
        <select id="category" name="category">
          <option value="tourism">観光名所</option>
          <option value="gourmet">食事処</option>
          <option value="public">公共施設</option>
          <option value="emergency">緊急</option>
        </select>
      </div>
      <input class="inputContent__btn" type="submit" value="追加">
    </form>
  </div>
</div>

</body>
</html>